apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecretList
metadata:
  name: example-static-secret-list
spec:
  vaultAuthRef: my-vault-auth
  items:
    - mount: secret
      path: myapp/config
      destination:
        name: app-config-secret
        create: true
        type: kubernetes.io/env
    - mount: secret
      path: anotherapp/credentials
      destination:
        name: another-secret
        create: true
        type: kubernetes.io/opaque
